### PR TITLE
Drop python2

### LINKED ISSUE #1892: python2 will be unmaintaned soon
## Is your feature request related to a problem? Please describe.
Python 2.7 will not be maintained past 2020, see: https://pythonclock.org/
A lot of packages also drop `python2.7` support: https://python3statement.org/

## Why does polybar need this feature?
Some critical bug can be found in `python2.7` which will not be fixed. Also, many users will remove `python2.7` from their machines.

## Describe the solution you'd like
User `python3.*` instead and `python3` libraries & dependencies.

## Describe alternatives you've considered
Stop using python (it seems, this project doesn't have a lot of python code)

## Additional context
I can't remove `python2.7`from Gentoo right now only because `polybar` requires it:
```
!!! The ebuild selected to satisfy "x11-misc/polybar" has unmet requirements.
- x11-misc/polybar-3.2.1::gentoo USE="alsa curl ipc network -i3wm -mpd -pulseaudio" ABI_X86="(64)" PYTHON_TARGETS="-python2_7"

  The following REQUIRED_USE flag constraints are unsatisfied:
    python_targets_python2_7
```

### PR DESCRIPTION
**Pull request by patrick96**
So this didn't take as much work as I thought.

On my machine this code generates the same `.hpp` files as the python2 code (except for the order of classes).

@Lomadriel could you please try this and see if the files generated in `include/xpp/proto` are the same for you as well (make sure to clear the directory before you build).

Fixes polybar/polybar#1892

### CODE REVIEW

**Comment by Lomadriel** [comment]
Just a little question, did you pass on all the code or did you fix problems when your python script crashed ?

**Comment by patrick96** [comment]
I ran `make xpp` and then tried to fix whatever error popped up until it no longer crashed.

It's very well possible that there are some pieces of code that won't work with python3.

I will try to run some linters over the code to see if I find anything. Honestly I'm not sure how to find *all* incompatibilites, even the [Porting Guide](https://docs.python.org/3/howto/pyporting.html) suggests having high code coverage to find errors.

**Review by Lomadriel — APPROVED** [review]
I tried to look, seems okay for me even if the code is no very clean (use of variable declared in the scope of an if, …)

> It's very well possible that there are some pieces of code that won't work with python3.

If that so somebody will probably open an issue.

We should probably issue a new 3.4.X release of polybar.

**Comment by patrick96** [comment]
I fixed some more issues I found with other linters. But they seem to be in code that is never called anyway.

I think there really isn't another way than break the build for users where other pieces of the code are called.

**Pull request merged**
